from pathlib import Path
import hashlib
import re
import struct
import zlib

root = Path(__file__).resolve().parent
source = root.parents[2] / 'external/reshade/deps/stb_image/stb_image_write_hdr_png.h'
array = source.read_text().split('ICC_RGB_D65_202_Rel_PeQ[] =', 1)[1].split('};', 1)[0]
compressed = bytes(int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{2})', array))
profile = zlib.decompress(compressed)
assert hashlib.sha256(profile).hexdigest() == '997c850563e879797ea23fa8efc89a11d8395533df9b3f5e5e8ff3ece7e5b919'

def chunk(kind, data):
    return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data))

metadata = (
    chunk(b'sBIT', bytes((16, 16, 16)))
    + chunk(b'cICP', bytes((9, 16, 0, 1)))
    + chunk(b'iCCP', b'RGB_D65_202_Rel_PeQ\0\0' + compressed)
    + chunk(b'cHRM', struct.pack('>8I', 31270, 32900, 70800, 29200, 17000, 79700, 13100, 4600))
)
header = '''// Generated by screenshot_profile.py from ReShade's public-domain HDR PNG writer.
// ICC generated with libjxl, courtesy of ledoge. See generator for source and hash.
#pragma once
#include <array>
#include <cstdint>
namespace endfield::screenshots {
'''
header += f'inline constexpr std::array<uint8_t, {len(metadata)}> kHdrMetadataChunks = {{\n'
header += ''.join('  ' + ','.join(f'0x{v:02x}' for v in metadata[i:i+20]) + ',\n' for i in range(0, len(metadata), 20))
header += '};\n}\n'
(root / 'screenshot_profile.hpp').write_text(header)
